### ISSUE TITLE
Error "RuntimeWarning: coroutine 'get_token' was never awaited"

### ISSUE THREAD

**Issue by oakbrad** [Findus23/rss2wallabag#36]
First, thank you for your work on this - really appreciate it :)

I am trying to get my RSS feed of starred articles from TT-RSS into Wallabag.

I've created my config.yaml with my Wallabag info and my github username, and added into the sites.yaml the URL for my RSS feed:

```
tt-rss:
  tags:
  - ttrss
  url: http://myurl.com/rss-feed
```
With debug enabled, when I run "python3 main.py" I see it run through my github stars (and these are then populated into the sites.yaml file). I also see it ingesting my RSS feed:

```
2018-01-03 19:25:29,044 - INFO - tt-rss: Downloading feed
2018-01-03 19:25:29,044 - INFO - tt-rss: Parsing feed
2018-01-03 19:25:29,661 - INFO - Title of the most recent article in my feed: article found
```

But at the end of the debug info I'm seeing the error:
`sys:1: RuntimeWarning: coroutine 'get_token' was never awaited`
And nothing is added into Wallabag.

Any help greatly appreciated, I am a python novice so not sure where to go from here. Thank you!

**Comment by Findus23** [comment]
Hi,
Great that you like it.
Are you sure you are using version `1.1.0` of `wallabag-api`?
In version `1.2.0` it was completely rewritten to use asynchronous HTTP requests. I tried it but failed to adapt my script because I haven't tried `async` and `await` in python before.
Because of that I am staying with version `1.1.0`-

**Comment by Findus23** [comment]
I have now checked again and implementing async wasn't actually that hard. 
You can try it out on the `async` branch. 
https://github.com/Findus23/rss2wallabag/tree/async

Bonus: As all feeds are fetched at the same time it runs in 8 seconds instead of over 1 minute for my list of feeds.

**Comment by oakbrad** [comment]
You were right I had 1.2.0 installed. Downgrading and running again (on the main branch) I get:

```
2018-01-04 10:21:24,608 - INFO - Starting new HTTP connection (1): wallabag.myhost.com
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    token = Wallabag.get_token(**config["wallabag"])
  File "/usr/local/lib/python3.5/dist-packages/wallabag_api/wallabag.py", line 333, in get_token
    return cls.handle_json_response(r)['access_token']
  File "/usr/local/lib/python3.5/dist-packages/wallabag_api/wallabag.py", line 92, in handle_json_response
    raise HTTPError(responses.status_code, responses.json())
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 797, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Upgrading back to 1.2.0 and running the async branch:
```

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    loop.run_until_complete(main(loop, sites))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "main.py", line 58, in main
    token = await Wallabag.get_token(**config["wallabag"])
  File "/usr/local/lib/python3.5/dist-packages/wallabag_api/wallabag.py", line 549, in get_token
    data = await cls.handle_json_response(resp)
  File "/usr/local/lib/python3.5/dist-packages/wallabag_api/wallabag.py", line 102, in handle_json_response
    message=await responses.json())
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 730, in json
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
```

Appreciate the help

**Comment by Findus23** [comment]
Hi,

That seems to be the same error in both cases.

Before running the script needs to get an access token (`token = Wallabag.get_token(**config["wallabag"])`). The error occurs inside the wallabag-api library. It tries to fetch some JSON data (probably the API that returns the access token),but it gets an HTML page instead and can't continue.
It's possible that this is an error in Wallabag. Maybe its log or the PHP log shows more. Did you check if the client_id, client_secret, username and password are correct? I don't know how the library reacts if they are wrong.

**Comment by oakbrad** [comment]
My mistake I had tried adding a / to my URL earlier and forgot to take it back off. It runs (very fast!!) and finds the articles but they're not appearing in Wallabag. With debug on I don't see any errors.

```
2018-01-04 12:57:39,372 - INFO - Parsing feed: tt-rss
2018-01-04 12:57:39,556 - INFO - article found: Recipe: Gnocchi Skillet with Chicken Sausage &amp; Tomatoes — Recipes from The Kitchn
2018-01-04 12:57:39,557 - INFO - add to wallabag: Recipe: Gnocchi Skillet with Chicken Sausage &amp; Tomatoes — Recipes from The Kitchn
2018-01-04 12:57:39,557 - INFO - article found: External 3.5″ SATA USB 3.0 enclosure #3DThursday #3DPrinting
2018-01-04 12:57:39,557 - INFO - add to wallabag: External 3.5″ SATA USB 3.0 enclosure #3DThursday #3DPrinting
```

Same behavior with the main branch and 1.1.0 wallabag-api. In my access logs I see:

```
x.x.x.x - - [04/Jan/2018:13:05:11 -0800] "POST /oauth/v2/token HTTP/1.1" 200 512 "-" "python-requests/2.5.0 CPython/3.5.2 Linux/4.4.0-103-generic"
x.x.x.x - - [04/Jan/2018:13:05:51 -0800] "POST /oauth/v2/token HTTP/1.1" 200 512 "-" "python-requests/2.5.0 CPython/3.5.2 Linux/4.4.0-103-generic"
x.x.x.x - - [04/Jan/2018:13:06:28 -0800] "POST /oauth/v2/token HTTP/1.1" 200 512 "-" "python-requests/2.5.0 CPython/3.5.2 Linux/4.4.0-103-generic"
```
No errors

**Comment by Findus23** [comment]
Hi,

The only thing I can think of is that debug isn't disabled (I added that yesterday so I can test it easier).
Have you added `debug: false` to the `config.yaml`?

**Comment by oakbrad** [comment]
My mistake again, didn't realize debug would prevent it from posting. All is working now, thank you so much for the hand holding and the great script :)
